language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1
  - 2.3.3
  - 2.2.7

env: "RAILS_ENV=test DISPLAY=:99.0"
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
    - rvm: rbx-2
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.1.gemfile

