language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2

env: "RAILS_ENV=test DISPLAY=:99.0"
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile

before_install:
  - sudo apt-get install chromium-chromedriver -y
addons:
  apt:
    update: true